### ISSUE TITLE
주문

### ISSUE THREAD

**Issue by suyeonkwong** [E-TF/Fresh-place#29]
- [x] db 배송정보 컬럼 추가된거 dto 변경  0.2d 2022-11-28
  - [x] 충돌 해결  0.1d 2022-11-28
  - [ ] 이벤트로 결제 되는방식으로 변경하기 2d    *(제일 중요) 
  - [x] 주문성공에 대한 테스트 1d 2022-12-08
  - [ ] 주문 실패 2d
  - [ ]  주문 취소1d

**Comment by yyy9942** [comment]
@suyeonkwong 일정에 대한 공수산정과 완료시점 같이 적어주세요~
