### ISSUE TITLE
아이템 조회의 캐시 사용 유무에 따른 부하 테스트 결과 

### ISSUE THREAD

**Issue by suyeonkwong** [E-TF/Fresh-place#37]
+ redis 사용 할 때
![redis](https://user-images.githubusercontent.com/80368511/212335643-d7bef32c-1465-4e12-aa9f-8e43401f674c.PNG)
 + redis 사용 안 할 때
![no_redis](https://user-images.githubusercontent.com/80368511/212335714-52721f59-55c0-49d3-9a69-5954fd4bc0da.PNG)
 + CPU 사용률
![cpu사용률](https://user-images.githubusercontent.com/80368511/212336778-74231f25-aa72-406a-a47c-13e4fe462a20.PNG)
 + 결과
TPS 3배 차이, CPU사용률 2배 차이.

![image](https://user-images.githubusercontent.com/80368511/214161580-694e9c2d-29ab-43d7-95b1-65f3fa86e317.png)
테스트를 어떻게 하냐에 따라 TPS도 다르게 나오고 GC수행 될 때 죽는부분도 있다. 
일단 여러개 해본 결과 TPS가 제대로 나올 때 평균 1.6배 정도 차이가 난다.

**Comment by yyy9942** [comment]
TPS가 순간적으로 줄어드는건 GC의 영향인듯한데, GC튜닝도 해보시면 좋을거같습니다
